<?
if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true) die();

$arTemplateDescription = array(
	"NAME" => GetMessage("MENU_DOT_DEFAULT_NAME"),
	"DESCRIPTION" => GetMessage("MENU_DOT_DEFAULT_DESC"),
    
    "INOBITEC.MENU.TOP_BASKET.BASKET" => GetMessage("INOBITEC.MENU.TOP_BASKET.BASKET"),


    "INOBITEC.MENU.TOP_BASKET.GOTOBASKET" => GetMessage("INOBITEC.MENU.TOP_BASKET.GOTOBASKET"),

    
    "INOBITEC.MENU.TOP_BASKET.TOTAL" => GetMessage("INOBITEC.MENU.TOP_BASKET.TOTAL"),

    
    "INOBITEC.MENU.TOP_BASKET.VIEWER" => GetMessage("INOBITEC.MENU.TOP_BASKET.VIEWER"),

    "INOBITEC.MENU.TOP_BASKET.EDITION" => GetMessage("INOBITEC.MENU.TOP_BASKET.EDITION"),

    "INOBITEC.MENU.TOP_BASKET.RUB_BIG" => GetMessage("INOBITEC.MENU.TOP_BASKET.RUB_BIG"),

    "INOBITEC.MENU.TOP_BASKET.RUB_SMALL" => GetMessage("INOBITEC.MENU.TOP_BASKET.RUB_SMALL"),

    "INOBITEC.MENU.TOP_BASKET.ITEMS" => GetMessage("INOBITEC.MENU.TOP_BASKET.ITEMS"),

    "INOBITEC.MENU.TOP_BASKET.SERVER" => GetMessage("INOBITEC.MENU.TOP_BASKET.SERVER"),

    "INOBITEC.MENU.TOP_BASKET.CONNECTIONS" => GetMessage("INOBITEC.MENU.TOP_BASKET.CONNECTIONS"),

);
?>